version: '3.8'

services:
  fig-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app/fig
      - /app/fig/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]